apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: eck
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: best-effort-xsmall
      count: 1
      storageClass: tanzu-supervisor-cluster-raid-1
    workers:
      class: best-effort-xsmall
      count: 1
      storageClass: sna-high
  settings:
    storage:
      classes: ["sna-high"]              #Named PVC storage classes
      defaultClass: sna-high                     #Default PVC storage class
