apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: eck
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: best-effort-xsmall
      count: 1
      storageClass: sna-high-iops
    workers:
      class: best-effort-xsmall
      count: 1
      storageClass: sna-high-iops
  settings:
    storage:
      classes: ["sna-high-iops"]              #Named PVC storage classes
      defaultClass: sna-high-iops                     #Default PVC storage class
