apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: eck
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: best-effort-xsmall
      count: 1
      storageClass: tanzu-supervisor-cluster-raid-1
    workers:
      class: best-effort-xsmall
      count: 1
      storageClass: tanzu-supervisor-cluster-raid-1
  settings:
    storage:
      classes: ["tanzu-supervisor-cluster-raid-1"]              #Named PVC storage classes
      defaultClass: tanzu-supervisor-cluster-raid-1                     #Default PVC storage class
